version: '3.9'

networks:
  deploy-apicar:
   driver: bridge
services:
  app:
    container_name: carapi
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres_db
    networks:
      - deploy-apicar

  postgres_db:
    container_name: postgres
    image: postgres:latest    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CarApiDb   
    ports:
      - "5432:5432"    
    networks:
      - deploy-apicar
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: